nodejs/nan

nan.h
nan_implementation_12_inl.h
nan_new.h
test/cpp/morenews.cpp

io.js ships a newer V8 version where String::ExternalAsciiStringResource
has been replaced with String::ExternalOneByteStringResource.
This change makes nan compile again with V8 3.29 and up.
Fixes #222.
R=@kkoopa @rvagg

Make compatible with io.js

---

Makefile
nan.h
test/binding.gyp
test/cpp/asyncprogressworker.cpp
test/js/asyncprogressworker-test.js

This builds on NanAsyncWorker by providing a NanAsyncProgressWorker which can dispatch progress information back to the originator.

Implement progress to NanAsyncWorker.

---

nan_implementation_12_inl.h

Fix the following build error when building with clang++:
In file included from ../cpp/asyncprogressworker.cpp:13:
In file included from ../../nan.h:63:
../../nan_new.h:207:43: error: inline declaration of 'NanNew' follows non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Handle<T> h);
^
../../nan_implementation_12_inl.h:218:1: note: previous definition is here
NanNew(v8::Handle<T> h) {
^
In file included from ../cpp/asyncprogressworker.cpp:13:
In file included from ../../nan.h:63:
../../nan_new.h:208:43: error: inline declaration of 'NanNew' follows non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Persistent<T> const& p);
^
../../nan_implementation_12_inl.h:224:1: note: previous definition is here
NanNew(v8::Persistent<T> const& p) {
g++ …

Fix non-inline definition build error with clang++

---

nan_implementation_12_inl.h
nan_implementation_pre_12_inl.h
nan_new.h
test/cpp/nannew.cpp

Added `String` constructors that were inadvertently omitted in the `NanNew` rewrite.
Fixes #227.
R=@agnat

Readded missing String constructors.

---

nan_new.h
test/cpp/nannew.cpp

This PR fixes #242. Turns out I initially proposed exactly the wrong fix. Using a function template specialization just doesn't work:
1. You can't come up with default arguments for a full specialization. (Kind of obvious)
2. Less obvious: Full specializations are *not* part of the overload set. See http://www.gotw.ca/publications/mill17.htm
So, we need to do the other thing. Instead of using a specialization, like:
````c++
template <>
typename NanIntern::Factory<v8::FunctionTemplate>::return_t
NanNew<v8::FunctionTemplate>(NanFunctionCallback callback) {
return NanIntern::Factory<v8::FunctionTemplate>::New(callback);
}
````
we're going to use an overload:

Fix #242: Disambiguate function pointer arguments

---

README.md
nan.h
nan_implementation_12_inl.h
nan_implementation_pre_12_inl.h
nan_new.h
test/cpp/nannew.cpp

Added `NanNew<Context>` and deprecated `NanNewContextHandle`. Scheduled for 1.6.0.
R=@agnat

Context Constructor

---

test/binding.gyp

Wundef and Wshadow produce too much noise from v8 and node. Maybe it is possible to selectively ignore them from these sources? This probably needs conditioning on other compilers (msvc, clang).
RFC

Enabled more compiler warnings.

---

nan.h

windows: Limit the scope of disabled warning C4530.

---

test/cpp/nannew.cpp

msvc does not like imlpicit boolean conversion
Is this the right way to fix it?
What if I use an unsigned int?
Would it be better to do this?
```c++
template<>
inline typename NanIntern::Factory<v8::Boolean>::return_t
NanNew<v8::Boolean, A0>(A0 arg0) {
return NanIntern::Factory<v8::Boolean>::New(arg0 != 0);
}
```
Should the above then be complemented with this?
```c++
template<>
inline typename NanIntern::Factory<v8::Boolean>::return_t
NanNew<v8::Boolean, bool>(A0 arg0) {
return NanIntern::Factory<v8::Boolean>::New(arg0);
}
```
R=@agnat

windows: Circumvent warning C4800

---

nan.h

Support joyent/node 0.11.15

---

appveyor.yml

Try this one. Should run fine if I didn't miss something.

appVeyor improvements

---

Makefile
nan.h
nan_string_bytes.h
test/cpp/strings.cpp
test/js/strings-test.js

`node::Encode` expects `const char *`, not `const void *`.
Fix #272

NanEncode: fix argument type for node::Encode

---

test/cpp/nannew.cpp

@agnat This fails. What is the correct fix? An overload?
```
../../nan_new.h: In instantiation of ‘typename NanIntern::Factory<T>::return_t NanNew(A0, A1) [with T = v8::Context; A0 = long int; A1 = v8::Handle<v8::ObjectTemplate>; typename NanIntern::Factory<T>::return_t = v8::Local<v8::Context>]’:
../cpp/nannew.cpp:110:8:   required from here
../../nan_new.h:215:47: error: invalid conversion from ‘long int’ to ‘v8::ExtensionConfiguration*’ [-fpermissive]
return NanIntern::Factory<T>::New(arg0, arg1);
```

Test NanNew<Context> better.

---

nan.h

`node::ObjectWrap::handle()` should get a const qualifier

Replaced NanObjectWrapHandle macro with function

---

nan.h
test/cpp/nannew.cpp
test/cpp/returnvalue.cpp
test/js/returnvalue-test.js

This should give some more convenience. Note that new v8 already allows returning primitives and silently wraps them in v8 types.

Allow primitives with NanReturnValue

---

nan.h
test/binding.gyp
test/cpp/threadlocal.cpp
test/js/threadlocal-test.js

This makes thread local storage available to older versions of libuv as well.  It is essentially a backport of libuv/libuv@5d2434bf71e47802841bad218d521fa254d1ca2d, written by Ben Noordhuis.  But the names were changed, and the functions were turned into inline functions to avoid having the same non-inline function in multiple translation units.  The test is a lot more node-based, even if the things to test more or less follow those tested in libuv.

Ticket #306: Backport thread local storage

---

README.md

Add a section that explains how to modify C++ code for NAN.
<table><tbody>
<tr><th>Aspect</th><th>Without NAN</th><th>With NAN</th></tr>
<tr><td>Function declaration</td><td><pre>class MyClass : ObjectWrap {
....
static Handle<Value> ToString(const Arguments& args);
....
}</pre></td></th><td><pre>class MyClass : ObjectWrap {
....
static NAN_METHOD(ToString);
....
}</pre></td></tr>
<tr><td>Function definition</td><td><pre>Handle<Value>
MyClass::ToString(const Arguments& args)
{
HandleScope scope;
....
}</pre></td></th><td><pre>
NAN_METHOD(MyClass::ToString)
{
NanScope();
....
}</pre></td></tr>
<tr><td>Return a value</td><td><pre>return scope.Close(result);</pre></td></th><td><pre>NanReturnValue(result);</pre></td></tr>
<tr><td>Return undefined</td><td><pre>return …

Add porting guide to readme

---

nan_implementation_12_inl.h
nan_implementation_pre_12_inl.h
nan_new.h
test/cpp/nannew.cpp
test/cpp/news.cpp

Remove support for signatures with arguments

---

README.md

Proposing a governance structure compatible with the io.js project, in preparation for a move to the _iojs_ GitHub org.
Note that this is based on the bootstrap governance structure with the following broad changes:
* No distinction between WG members and "Collaborators", there is only one level of hierarchy here as there has always been
* No requirement for meetings, everything can be done via GitHub as it always has been done
* No conduct section
Collaborators please review and please comment on whether you'd like to transfer to the io.js Working Group.
Obvious members of the NAN WG:
* @rvagg
* @kkoopa
* @brett19
* @bnoordhuis
* @agnat
@trevnorris and @TooTallNate, I'm unsure of whether you're still interested in participating in this project. I'd love you both to continue to be …

Added io.js WG governance section

---

Makefile
nan.h
test/binding.gyp
test/cpp/objectwraphandle.cpp
test/js/objectwraphandle-test.js

This will be published ASAP as 1.8.1
Fixes a problem in https://github.com/iojs/nan/commit/0bc6d599f23bd00d389461ec4effa88cac7c9baf where the argument type was accidentally changed from pointer to reference.

NanObjectWrapHandle should take a pointer

---

nan.h

In https://github.com/sass/node-sass/issues/892
we have a report that node-sass compilation
may fail due to undefined abort().
I think we should not rely on node or uv to
include <stdlib.h> for us.
http://pubs.opengroup.org/onlinepubs/9699919799/functions/abort.html

Use <cstdlib> for abort()

---

nan.h

Fixes #330
Made the same changes to `NanAsyncWorker`, since it too contains a `Persistent<T>`.
PTAL

No copy or move in NanCallback and NanAsyncWorker

---

Makefile
nan.h

Fatalexception

---

nan.h
test/cpp/nancallback.cpp
test/js/nancallback-test.js

As a way of addressing #284, I added a dereference operator to `NanCallback` as a shorthand for `GetFunction`. I also added a function call operator as a shorthand for `Call`.
Should be included in #365.

Add dereference and function call operators to NanCallback

---

package.json

`node-gyp` had been using http://nodejs.org for downloading node.js source. This was recently changed in https://github.com/TooTallNate/node-gyp/pull/656 to use https:// instead. Bump dependency to pick up that change.

Bump dependency on node-gyp to 2.0.2 to pick up https:// downloading of node.js source

---

nan.h

`v8::String::REPLACE_INVALID_UTF8` was added in node.js v0.10.29.
Check the version macros to see if it's available.
Fixes: https://github.com/nodejs/nan/issues/394
Fixes: https://github.com/nodejs/nan/issues/396
R=@kkoopa, /cc @rvagg @Raynos
I think we should address this, I'm getting complaints from people about broken builds separate from the filed issues.

Add workaround for missing REPLACE_INVALID_UTF8

---

nan_weak.h

Replace `wbcd->invoke` with `WeakCallbackInfo<P>::invoke` when passing
it as a callback.  The former is not proper syntax although sometimes
(but not always) accepted by compilers.
Should fix the following build error that people have been reporting:
nan_weak.h:363:42: error: cannot create a non-constant pointer to
member function
v8::PersistentBase<T>::SetWeak(wcbd, wcbd->invoke);
Fixes: https://github.com/strongloop/fsevents/issues/80
R=@kkoopa

Don't use clang++ / g++ syntax extension.

---

README.md
doc/methods.md

Replace broken references which referred to `methods.md#api_nan_property_callback_info` instead of `methods.md#api_nan_return_value`

Fix references to Nan::ReturnValue

---

.travis.yml

This change allows travis to use sudo-less containers which start in seconds.
http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F

travis: set CXX environment variable instead of using update-alternatives

---

test/cpp/objectwraphandle.cpp
test/js/objectwraphandle-test.js

Fixes warning about unused member variable

Add test for getting wrapped value to ObjectWrap test suite

---

nan_implementation_12_inl.h
nan_implementation_pre_12_inl.h

This should make `New<FunctionTemplate>()` work.
/cc @rvagg

Properly handle null callback in FunctionTemplate factory

---

nan_implementation_12_inl.h
nan_implementation_pre_12_inl.h

They were added in commit 12948c68 ("Remove NanReturn* macros") but
have never been in use as far as I can tell.
R=@kkoopa

Remove unused static std::map instances.

---

doc/maybe_types.md

Was pointing to CallAsFunction() at v8docs

Fix target on v8::Object#CallAsConstructor()

---

nan.h

I'm guessing https://github.com/mikemorris/nan/blob/master/test/js/buffer-test.js#L19 didn't catch this because the scope doesn't change?

EscapableHandleScope in Nan::NewBuffer for Node 0.8 and 0.10

---

doc/methods.md

This patch does the following
- Completes the backtick in `PropertyCallbackInfo`
- Separates code from the explanation in "Method declaration" section
- Aligns the parameters in the signatures to the first parameter
- Separates two signatures with `;` so that they both will be Syntax highlighted.

doc: fix minor formatting errors

---

README.md
doc/node_misc.md
doc/object_wrappers.md
test/cpp/objectwraphandle.cpp

Keeps documentation of `Nan::ObjectWrapper` on its own page, along with examples to reflect the documentation at https://nodejs.org/api/addons.html:
- basic wrapped object
- wrapped object factory
- passing wrapped objects around
The examples are derived from the existing tests, with some adaptations and `using namespace` statement(s) removed. I tested the C++ code in the examples (with all `using namespace` statement(s) removed) to be sure that they will compile and run correctly. To be honest they are not so easy to understand for a beginner but I figure they would be better than having no samples.

Basic documentation of object wrappers on its own page, with sample code

---

tools/1to2.js

You probably meant to read the tool's package.json, not whichever package.json happens to be in CWD.

Fixed package.json read

---

doc/object_wrappers.md
test/cpp/accessors.cpp
test/cpp/accessors2.cpp
test/cpp/indexedinterceptors.cpp
test/cpp/namedinterceptors.cpp
test/cpp/objectwraphandle.cpp
test/cpp/wrappedobjectfactory.cpp
test/js/accessors-test.js
test/js/objectwraphandle-test.js

This is after reading [Christian 'Little Jim' Plesner's answer to “What is the difference between Arguments::Holder() and Arguments::This()?”](https://groups.google.com/d/msg/v8-users/Axf4hF_RfZo/hA6Mvo78AqAJ) in the context of [my Stack Overflow question “This vs. Holder for ObjectWrap::Unwrap”](http://stackoverflow.com/q/34257458/1468366). Without the fix in my second commit, the test case from my first commit can lead to a failed assertion on Node 0.10. The change is also in line with [the `node::ObjectWrap` documentation](https://nodejs.org/api/addons.html#addons_wrapping_c_objects).

Pass Holder instead of This to ObjectWrap::Unwrap

---

nan.h

Types were unified in https://codereview.chromium.org/1298113003
This change went into v8 4.6 which made it into Node 5. The
GC*logueCallback types have gone away completely in 4.9.

Rename GC*logueCallback to GCCallback for >4.0

---

examples/async_pi_estimate/addon.js

Right now, both tabs and spaces are mixed (in some weird way) in this file, making it look strangely in some editors.

Use only spaces for indentation in addon example

---

nan.h

There's no need to check if a pointer is equal to NULL prior to deleting it, as deleting a null pointer is a no-op ([source](http://en.cppreference.com/w/cpp/language/delete), search for "expression evaluates to a null pointer value").

Remove null pointer checks

---

Makefile
doc/asyncworker.md
nan.h
test/binding.gyp
test/cpp/asyncprogressworkersignal.cpp
test/js/asyncprogressworkersignal-test.js

I'd like the ability to efficiently send progress without data. Since `uv_async_send` coalesces callbacks, it's probably must more common for people to implement data callbacks with a queue as a member variable anyways.

Dataless progress callbacks for AsyncProgressWorker

---

nan.h

See [0] and [1]: starting with node.js v6, setting non-primitive values
on FunctionTemplate and ObjectTemplate instances is discouraged; v7 will
downright disallow it.  Update `Nan::SetPrototypeMethod()`.
[0] https://github.com/nodejs/node/issues/6216
[1] https://github.com/nodejs/node/pull/6228

Don't use deprecated v8::Template::Set().

---

nan.h
package.json
test/cpp/settemplate.cpp

As discussed in #564 here is a first stab at refactoring `SetMethod(...)`. @kkoopa, @bnoordhuis PTAL and let me know what you think.

Refactor SetMethod(...)

---

nan.h
nan_implementation_12_inl.h
nan_maybe_43_inl.h

Current deprecation warnings on Node v6 are SetAccessor, CloneElementAt,
and BooleanObject::New.

Remove V8 deprecation warnings

---

nan_weak.h

Fix new versions not to use WeakCallbackInfo::IsFirstPass

---

nan.h
nan_callbacks_pre_12_inl.h
nan_converters.h
nan_maybe_43_inl.h
nan_maybe_pre_43_inl.h
nan_persistent_12_inl.h
nan_persistent_pre_12_inl.h
nan_typedarray_contents.h
nan_weak.h

There is no reason to mark everything  `__attribute__((always_inline))`,
just use the regular keyword and let the compiler decide.  Avoids code
bloat and build errors when inlining fails due to compiler limitations.
Fixes: https://github.com/nodejs/nan/issues/576

Replace NAN_INLINE with 'inline' keyword.

---

.travis.yml
appveyor.yml

edit: does this even make sense here? I basically wanted to duplicate the commit for Node 6, but since @nodejs doesn’t have Travis enabled, I’m not so sure anymore…

Test on Node 7

---

nan.h
nan_typedarray_contents.h

Section 3.2 of the C++ standard states that destructor definitions
implicitly "use" operator delete functions. Therefore, these operator
delete functions must be defined even if they are never called by
user code explicitly.
http://www.open-std.org/JTC1/SC22/WG21/docs/cwg_defects.html#261
gcc allows them to remain as empty definitions. However, not all
compilers allow this.
This pull request creates definitions which if ever called, result
in an abort.

abort in delete operators that shouldn't be called

---

Makefile

remove repeated cpp source files in LINT_SOURCES:
* isolatedata.cpp
* makecallback.cpp
* morenews.cpp
closes https://github.com/nodejs/nan/issues/654

Makefile: remove repeated cpp files in LINT_SOURCES

---

README.md

newline is required before `##` headings to render properly on markdown renderers used on websites other than github, such as npmjs.
closes https://github.com/nodejs/nan/issues/652

README.md: newline is required before `##` headings to render properly

---

.travis.yml
Makefile
README.md
doc/.build.sh
doc/json.md
nan.h
nan_json.h
package.json
test/binding.gyp
test/cpp/json-parse.cpp
test/cpp/json-stringify.cpp
test/js/json-parse-test.js
test/js/json-stringify-test.js

As the V8 API for the `JSON` object has changed over the versions of V8 used in node, it makes good sense to add a helper for it, especially now that the `Stringify` method has been made available in node 7.
`v8::JSON` has two methods, `Parse` and `Stringify` ...  For a link to the v8 docs used in node 7, see [v8::JSON Class Reference](https://v8docs.nodesource.com/node-7.4/da/d6f/classv8_1_1_j_s_o_n.html)
As for the changes in `v8::JSON` in the versions of node supported by _NAN_:
`v8::JSON::Parse` was first available in node version 0.12.x - it is *not* otherwise available in versions 0.8 or 0.10.x
`v8::JSON::Stringify` was first available in node version 7 - it is *not* otherwise available in earlier versions
closes https://github.com/nodejs/nan/issues/650

nan: add support for JSON::Parse & Stringify

---

CHANGELOG.md

This one obviously is not urgent.  I noticed this typo in the changelog for 2.6.1...

CHANGELOG.md: fix typo in version stamp for 2.6.1

---

nan.h

My original pull request #651 added my name to the contributors block in _package.json_, but I forgot to add it to the top of _nan.h_.  If nobody minds, this PR adds it.  I didn't add myself to _README.md_ because the list in that file is for WG Members.

nan.h: update NAN contributors copyright header

---

nan_json.h
test/binding.gyp
test/cpp/accessors.cpp
test/cpp/accessors2.cpp
test/cpp/indexedinterceptors.cpp
test/cpp/makecallback.cpp
test/cpp/namedinterceptors.cpp
test/cpp/objectwraphandle.cpp
test/cpp/settemplate.cpp

Use the non-deprecated overload that takes a `v8::Isolate` pointer and
returns a `v8::MaybeLocal<v8::Value>` when building against node <= 6.
Fixes: #663

Fix v8::JSON::Parse() deprecation warning.

---

CHANGELOG.md

Fixes GitHub rendering the entire changelog with a strikethrough because of `<S>` ([see the current changelog](https://github.com/nodejs/nan/blob/5d358f26b34ee86a2a40bdf93c0dd620afad4d37/CHANGELOG.md)).

Fix GitHub rendering the entire changelog with a strikethrough

---

test/cpp/asyncprogressworker.cpp
test/cpp/asyncprogressworkersignal.cpp
test/cpp/asyncprogressworkerstream.cpp

Delete progress callback in `AsyncProgressWorker` test class destructors
In `test/cpp/asyncprogressworker*.cpp`, the addon functions allocate two
`Nan::Callback` objects, called `progress` and `callback`.
`callback` is passed into the `AsyncWorker` constructor, and gets
deleted by the `AsyncWorker` destructor after work is complete.
`progress` is passed into the user-level test class.  It is called
in `HandleProgressCallback()` but it never gets deleted.
Since this has been approved, I've also updated my other PR #692 that touches `AsyncProgressWorker` with a similar fix...
closes #698

Fix memory leak in the AsyncProgressWorker tests

---

Makefile
README.md
doc/asyncworker.md
nan.h
test/binding.gyp
test/cpp/asyncprogressqueueworker.cpp
test/js/asyncprogressqueueworker-0ms-test.js
test/js/asyncprogressqueueworker-1ms-test.js
test/js/asyncprogressqueueworker-test.js
test/js/asyncprogressworker-1ms-test.js

add `AsyncProgressQueueWorker`: wake the main thread like AsyncProgressWorkerBase, except all events are queued and delivered
There are often cases where we want to handle events initiated by threads other than node threads.  Developers are often told to look at `AsyncProgressWorker` , which allows us to send progress updates from external threads, but this is not necessarily enough.  `AsyncProgressWorker` does what it needs to do, but if it is invoked many times before it wakes the main thread, only the last event will be delivered.  This is great for sending "progress" style events, but sometimes we need to make sure that all events get delivered.  `AsyncProgressWorker` doesn't do the job in those cases.
This PR refactors `AsyncProgressWorkerBase` to separate common elements and adds a …

add AsyncProgressQueueWorker to queue and deliver all events

---

nan.h

`AsyncProgressQueueWorker` doesnt support `ExecutionProgress.Signal()`
If we leave things as-is, `AsyncProgressQueueWorker::ExecutionProgress.Signal()` is a no-op.  We can try to fix that, but there isn't any point.  If somebody wants that functionality, they should just use an `AsyncProgressWorkerBase<T>`  Let's just remove the entry point by swapping out the `AsyncBareProgressWorker<T>` with a specialized `AsyncBareProgressQueueWorker<T>` that simply doesn't have an `ExecutionProgress.Signal()`

AsyncProgressQueueWorker doesnt support ExecutionProgress.Signal()

---

doc/asyncworker.md

`AsyncProgressQueueWorker::ExecutionProgress::Signal()` was never supported.
It was removed in f3cdf8d2ed89728b6994dbb568b902ea80203177
Update the markdown docs to reflect this.

doc/asyncworker.md: remove AsyncProgressQueueWorker::ExecutionProgress::Signal

---

Makefile
test/binding.gyp
test/cpp/asyncprogressqueueworkerstream.cpp
test/js/asyncprogressqueueworkerstream-test.js

`AsyncProgressQueueWorker<T>` is a better choice over `AsyncProgressWorker<T>` when it comes to streaming, in most cases.  As such, we should include an example of how to use it.
This pull request adds an `AsyncProgressQueueWorker` test for streams, similar to the test for `AsyncProgressWorker`.   So similar, in fact, that this test is copied exactly from the `AsyncProgressWorker` test, but with all sleeps removed.
* The first patch copies the old test to a new test.
* The second patch shows the changes that I made to accommodate `AsyncProgressQueueWorker<T>`

add AsyncProgressQueueWorker test for streams

---

nan_json.h

This fixes a compilation error on io.js 1 and 2. V8 4.2.77 (io.js 2.5.0) still uses `Parse(Local<String> json_string)`, and V8 4.4.63 (io.js 3.3.1) uses `Parse(Isolate *isolate, Local<String> json_string)`

Fix compiling on io.js 1 & 2

---

doc/v8_internals.md
examples/async_pi_estimate/async.cc
test/cpp/asyncprogressqueueworker.cpp
test/cpp/asyncprogressqueueworkerstream.cpp
test/cpp/asyncprogressworker.cpp
test/cpp/asyncprogressworkersignal.cpp
test/cpp/asyncprogressworkerstream.cpp
test/cpp/asyncworker.cpp
test/cpp/asyncworkererror.cpp
test/cpp/bufferworkerpersistent.cpp
test/cpp/nancallback.cpp
test/cpp/persistent.cpp
test/cpp/private.cpp
test/cpp/returnvalue.cpp
test/cpp/weak.cpp
test/cpp/weak2.cpp

Since a new release seems to be looming around the corner, better to fix these now...
Expanding on bnoordhuis' suggestion here: https://github.com/nodejs/nan/pull/702#discussion_r143352671
The changes are mostly in `test/cpp`, `doc` and `examples` but there were two callers of `To<v8::Function>`  in `nan_json.h` that got converted here as well.

convert uses of `val.As<Foo>()` to `To<Foo>(val).ToLocalChecked()`

---

nan_maybe_pre_43_inl.h

I think I agree with the compiler. The function was difficult to read. I think it's easier (and prettier) to just do as it says.
closes #717

nan_maybe_pre_43_inl.h: fix warnings in DefineOwnProperty()

---

CHANGELOG.md

Node versions have crawled up enough to make this confusing.

fix: confusing version heading

---

.travis.yml
README.md

As per https://github.com/nodejs/nan/pull/729#issuecomment-363618436, stop testing against Node.js 0.12 on OSX.

Drop osx builds with Node 0.12

---

Makefile
doc/node_misc.md
nan.h
test/binding.gyp
test/cpp/asyncresource.cpp
test/js/asyncresource-test.js

This commit adds support for the async context accepting versions of
node::MakeCallback. An async_context concept has been added as a
wrapper around node::async_context, along with APIs for initializing
and destroying async context, similar to how [N-API](https://nodejs.org/dist/latest-v9.x/docs/api/n-api.html#n_api_custom_asynchronous_operations) exposes this
functionality.
Ref: https://github.com/nodejs/node/issues/13254

introduce AsyncResource class

---

nan_maybe_43_inl.h

Fix compilation on io.js 3

---

Makefile
doc/asyncworker.md
doc/callback.md
nan.h
test/binding.gyp
test/cpp/asyncresource.cpp
test/cpp/asyncworker.cpp
test/cpp/callbackcontext.cpp
test/cpp/sleep.h
test/js/asyncworker-test.js
test/js/callbackcontext-test.js

There are three commits here. Each can be individually reviewed.
Background: https://github.com/nodejs/node/issues/13254.
Continuing on from #729, this adds async context support to Nan::Callback and Nan::AsyncWorker (and subclasses). 
I have not added any deprecations to the legacy `Nan::Callback::Call`s versions yet. I propose to do that in the next PR.

Add context awareness to Nan::AsyncWorker and Nan::Callback

---

doc/callback.md
doc/maybe_types.md
nan.h
test/cpp/asyncprogressqueueworker.cpp
test/cpp/asyncprogressqueueworkerstream.cpp
test/cpp/asyncprogressworker.cpp
test/cpp/asyncprogressworkersignal.cpp
test/cpp/asyncprogressworkerstream.cpp
test/cpp/bufferworkerpersistent.cpp
test/cpp/nancallback.cpp

Note: this builds on top of commits from #732. I will rebase after that PR lands.
Now that we have exposed the concept of `AsyncResource` to `Nan::Callback` and `Nan::AsyncWorker`, let's go ahead and deprecate the legacy `Callback::Call` functions that do not accept a context.
Related: deprecation of legacy `MakeCallback` in Node: https://github.com/nodejs/node/pull/18632

Deprecate old Callback::Call

---

nan.h
nan_json.h

I was about to publish 2.9.0 when I noticed spurious deprecation warnings. This should fix the problem. Since I have already tagged and pushed 2.9.0, I guess the best course of action is to skip publishing 2.9.0 to npm and jump directly to 2.9.1.

Deprecation warnings

---

nan.h
test/js/asyncresource-test.js
test/js/asyncworker-test.js
test/js/callbackcontext-test.js

Temporary fix disabling async_hooks for Node 8 below 8.6. Having some non-obvious issues with getting the older `async_hooks` API working. Addresses #735.

Bandaid for async hooks

---

test/cpp/asyncprogressworker.cpp
test/cpp/asyncprogressworkersignal.cpp
test/cpp/asyncprogressworkerstream.cpp
test/cpp/bufferworkerpersistent.cpp

A nice new `Sleep()` macro has been added in a header file.  Let's all use it.

test/cpp: deduplicate Sleep() macro

---

nan.h
test/cpp/asyncresource.cpp
test/cpp/asyncworker.cpp
test/cpp/callbackcontext.cpp
test/cpp/sleep.h

* Do not indent within a namespace  [runtime/indentation_namespace] [4]
* No #ifndef header guard found, suggested CPP variable is: TEST_CPP_SLEEP_H_  [build/header_guard] [5]
* Include the directory when naming .h files  [build/include] [4]
* Found C system header after other header. Should be: asyncworker.h, c system, c++ system, other.  [build/include_order] [4]

Linter cleanups

---

examples/async_pi_estimate/async.cc

👋 
Since `v8::Local<v8::Value> Call(int argc, v8::Local<v8::Value> argv[]);` is now deprecated (https://github.com/nodejs/nan/pull/733), I'm updating the example to use the new API.
before:
```
> node-gyp rebuild
CXX(target) Release/obj.target/addon/addon.o
CXX(target) Release/obj.target/addon/pi_est.o
CXX(target) Release/obj.target/addon/sync.o
CXX(target) Release/obj.target/addon/async.o
../async.cc:50:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
callback->Call(2, argv);
^
../node_modules/nan/nan.h:1567:3: note: 'Call' has been explicitly marked deprecated here
NAN_DEPRECATED inline v8::Local<v8::Value>
^
../node_modules/nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
^
1 warning generated.
SOLINK_MODULE(target) Release/addon.node
```
after:
```
> node-gyp …
```

Fix async_pi_estimate deprecation

---

Makefile
nan_define_own_property_helper.h
nan_maybe_43_inl.h
nan_maybe_pre_43_inl.h

This adds a new file called `nan_define_own_property_helper.h` that contains a deduplicated code block taken from very similar code between `nan_maybe_43_inl.h` and `nan_maybe_pre_43_inl.h `
To anyone looking and scratching their head as to how the code block in  `nan_maybe_43_inl.h` ever gets reached at all, this apparently happens in io.js 3 (see #725)
I wasn't sure what to name the common function, so I went with `DefineOwnPropertyHelper()`, but I'm open to other suggestions...
As discussed: https://github.com/nodejs/nan/pull/728#discussion_r167025257

deduplication of DefineOwnProperty() wrapper

---

doc/maybe_types.md
nan.h

While working on adapting node-sass to the new async context preserving mechanism to call, I noticed that it would be handy to have another overload.
This commit adds a non-receiver overload for Nan::Call to make it more comparable to Nan::Callback::Call.

add Nan::Call overload

---

nan_converters_43_inl.h

I have seen an unneeded call to Isolate::GetCurrent() in converters during stepping around. Even the overhead of this is small it's unneeded.

avoid unneeded call to Isolate::GetCurrent() in converters

---

nan.h
test/cpp/threadlocal.cpp

Presently we use MakeCallback throughout the codebase even in cases
where it doesn't make sense (sync calls). Add some more convenience
overloads for Nan::Call to allow such uses to be migrated over to
Nan::Call instead.
In lieu of coverage, change the Tap reverse bindings to use Nan::Call
to perform synchornous calls. This change exposes a timing issue in
one of the tests – fix it by properly calling Tap's t.end().

add more Nan::Call overloads

---

doc/node_misc.md
nan.h
test/cpp/makecallback.cpp
test/cpp/weak.cpp
test/cpp/weak2.cpp

This builds on top of #751. I will rebase when that lands.
This PR deprecates MakeCallback and removes remaining internal uses.
~~TODO: update the docs.~~

Deprecate makecallback

---

doc/object_wrappers.md

When compiling `info.GetReturnValue().Set(cons->NewInstance(argc, argv));` it gives the warning `'v8::Function::NewInstance': was declared deprecated`. This PR fixes it.

fix example deprecation

---

test/cpp/makecallback.cpp

fix test/cpp/makecallback.cpp:18: Single-parameter constructors should be marked explicit. [runtime/explicit] [5]

[LINT] Single-parameter constructors should be marked explicit

---

appveyor.yml

...at least until we figure out how to get past the SSL error
This will allow builds to go green if the only failure is `Environment: nodejs_version=0.8`
note:  this build still fails against nodejs version 10 due to the broken named interceptor test

appveyor.yml: allow failures against nodejs 0.8

---

test/js/strings-test.js

fix (node:11826) [DEP0005] DeprecationWarning:
Buffer() is deprecated due to security and usability issues.
Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Also, includes a check for whether Buffer.from is actually available :-)

use Buffer.from('text') rather than new Buffer('text') when available

---

test/cpp/accessors2.cpp
test/cpp/indexedinterceptors.cpp
test/cpp/namedinterceptors.cpp
test/cpp/nannew.cpp

fix warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]

test/cpp: replace `v8::String::Utf8Value` with `Nan::Utf8String`

---

test/cpp/namedinterceptors.cpp

The PropertyQuery callback needs to return _something_ in order for V8
to consider the property present in Node.js 10.
Fixes failing test test/js/namedinterceptors-test.js

Fix bugs in named interceptor test.

---

Makefile
test/cpp/typedarrays.cpp

* Add `test/cpp/typedarrays.cpp` to `Makefile` `LINT_SOURCES`
* typedarrays.cpp: Missing spaces around < [whitespace/operators] [3]

Fix typedarrays.cpp: Missing spaces around < [whitespace/operators] [3] 

---

nan.h
package.json
test/cpp/asyncresource.cpp
test/cpp/callbackcontext.cpp
test/tap-as-worker.js

This is necessary now that node is supporting multiple v8 isolates and uv event loops behind the `--experimental-worker` flag in node v10.5

Introduce a GetCurrentEventLoop function to get the current uv event loop

---

nan.h

Uses the named symbol `node_register_module_v##` variant of registration that works to support loading in multiple workers on node 10.5 with `--experimental-workers`.
This may need updating in the future if/when node requires native modules to explicitly opt in to multiple isolate support.

Add NAN_MODULE_WORKER_ENABLED macro as a replacement for NAN_MODULE that supports multiple workers

---

cpplint.py

__xrange()__ was removed in Python 3 in favor of __range()__.  This PR ensures similar functionality on both Python 2 and Python 3.
Discovered via https://travis-ci.com/nodejs/node/builds/79706150 (https://github.com/nodejs/node/pull/21942)
flake8 testing of https://github.com/nodejs/nan on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
/home/travis/virtualenv/python3.7.0/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
./cpplint.py:1398:12: F821 undefined name 'xrange'
for i in xrange(startpos, len(line)):
^
./cpplint.py:1627:15: F821 undefined name 'xrange'
for line in xrange(1, min(len(lines), 11)):
^
./cpplint.py:1755:12: …
```

Update cpplint.py for compatibility with Python 3

---

nan.h
nan_implementation_12_inl.h
package.json

Fixes: https://github.com/nodejs/node/issues/23122
~Also updates dependencies~

deps: adapt to V8 7.0

---

.npmignore

The 2.11.1 package at NPM includes a file nan-2.11.1.tgz - most likely npm pack was executed before npm publish.
I added nan-*.tgz to .npmignore to avoid this in future.

add nan-*.tgz to .npmignore

---

nan.h
test/cpp/nancallback.cpp
test/js/nancallback-test.js

Added a `scope.Escape()` in `Call()` as suggested by @addaleax in #813.
fixes: #813

Add scope.Escape() to Call()

---

README.md
doc/errors.md
doc/json.md
doc/maybe_types.md
doc/methods.md
doc/new.md
doc/persistent.md
doc/scopes.md
doc/script.md
doc/v8_internals.md
doc/v8_misc.md

Corrected links to v8 docs (used 8.11 where possible) as I got a 404 for the io-js-3.3 links.
Corrected a few copy/paste errors in docs.

[doc] fix links and a few copy paste errors

---

.travis.yml

node-gyp v3.6.3 doesn't work with node.js v0.8.28 any longer and
therefore the test suite doesn't build. As that is outside our
control, drop it.
In fact, it's a dependency of node-gyp that stopped working but
that is immaterial, the net result is the same.

Drop Node.js v0.8.x from Travis CI.

---

nan_weak.h
test/cpp/weak.cpp
test/js/weak-test.js

The definition of the SetWeak() template method constrained the type to
types with a GetAlignedPointerFromInternalField() method.  In practice
that meant it only worked with T=v8::Object.
Lift that restriction so that e.g. T=v8::External now also works.  Note
that `SetWeak(WeakCallbackType::kInternalFields)` for types without the
aforementioned method will result in a run-time assertion.
<hr>
I wrote this over a year ago but I forgot to PR it. I don't need it now but I did want it at the time and it still seems useful so here goes.

Allow SetWeak() for non-object persistent handles.

---

nan.h

The five argument WriteUtf8() method was introduced in Node.js v10.0.0,
it doesn't exist in older 10.x releases.
Use the four argument overload and a bunch of pragmas to silence the
compiler warnings.
Fixes: https://github.com/nodejs/nan/issues/832
Refs: https://github.com/nodejs/nan/pull/825

Fix build breakage with Node.js 10.0.0-10.9.0.

---

nan_converters_43_inl.h
nan_implementation_12_inl.h

This PR allows to use NAN with current Node on master and should fix several fails in CITGM which use NAN.
Not sure if this should be really included in NAN at this time as Node plans to do further updates of V8 till v12 is released (see https://github.com/nodejs/node/issues/25060#issuecomment-447748949).
There is still a self deprecation warning in v8 left but I think this should be addressed inside v8 or in the patched v8 variant included in node.
Refs: https://github.com/nodejs/node/issues/25060
Fixes: #829

add support for node master

---

nan_converters_43_inl.h
nan_implementation_12_inl.h

The changes introduced in https://github.com/nodejs/nan/commit/d113c0282072e7ff4f9dfc98b432fd894b798c2c make the (historically correct) assumption that it's impossible for an older version of node (and therefore an older version of V8) to have a higher NODE_MODULE_VERSION.
As of Electron `4.1.0` however this is not the case, it embeds node `10.11` with v8 `v6.9.427.24` but has the NMV of `69` which is higher than node 11's NMV of `68`.  As Electron continuously gets their own NMV numbers (refs https://github.com/nodejs/TSC/issues/651) we can't make this assumption any more.  Currently native modules are failing to build against Electron 4 because of this issue.
This PR updates these checks to check what actually matters here (the V8 version).
cc @kkoopa @Flarna

fix: check V8 version directly instead of inferring from NMV

---

nan_object_wrap.h

Remove use of `PersistentBase::IsNearDeath()` as it has been deprecated in V8 and it would causes compilation warnings in Node.JS 12.
I have not added any `ifdefs` here as it was used only within `asserts`.
Refs: https://github.com/nodejs/node/pull/26630

remove usage of deprecated IsNearDeath

---

Makefile
nan.h
nan_implementation_12_inl.h
nan_maybe_43_inl.h
nan_maybe_pre_43_inl.h
test/binding.gyp
test/cpp/maybe.cpp
test/cpp/morenews.cpp
test/cpp/multifile2.cpp
test/cpp/news.cpp
test/cpp/setcallhandler.cpp
test/cpp/threadlocal.cpp
test/js/maybe-test.js

Nan::Maybe<T> was an alias for v8::Maybe<T> with most Node.js versions
but that's problematic because v8::Maybe<T> has grown new methods over
time that are missing in older versions.
From now on we use our custom Maybe<T> implementation with all Node.js
versions. This commit also adds the following missing methods:
* Maybe<T>::Check() const
* Maybe<T>::To(T*) const
* Maybe<T>::ToChecked() const
Fixes: https://github.com/nodejs/nan/issues/851

Add missing methods to Nan::Maybe<T>

---

test/js/gc-fn.js
test/js/gc-test.js
test/js/weak-test.js
test/js/weak2-test.js

This allows folks running the `nan` tests in their own CI to run it without `--expose_gc` being supported as an incoming CLI flag.
The backstory here is I'm setting up some infra to run nan's test suite on Electron CI so that we know when things are gonna break as typically nowadays we are on the fringe of V8 👍

spec: add support for enabling gc at runtime in tests

---

appveyor.yml

Even though Node.js v12 is in the test matrix, it's not being tested. The cause is AppVeyor, which hasn't added v12 to its images just yet.
Luckily, there's a way to have AppVeyor install whatever Node version we want – using `Update-NodeJsInstallation`, which is present in all images.

fix: Install Node independent from AppVeyor images

---

README.md

I just removed "The V8 Embedders * Guide" link and leave "The V8 Getting Started * Guide", because both were moved to https://v8.dev/docs/embed

Change: update v8 embedders guide in README

---

Makefile
cpplint.py

Commit af24c7162be from 2018 allegedly also did that but it dies
silently for me and others with python 3.7.
This commit fixes the incompatibilities and adds an excepthook so
you get an indication of what the issue is.
Fixes: https://github.com/nodejs/nan/issues/884

Make cpplint.py compatible with python 3

---

test/cpp/nannew.cpp

V8 API for `ScriptOrigin` constructor has changed. Adapt test to compile with v8 8.9.
Currently only `ScriptOrigin` instances are consumed by NAN therefore no adaptions in the NAN API are needed to keep build/tests working.
fixes: #909

tests: adapt for v8 8.9

---

test/cpp/strings.cpp

Currently, the `strings` test in NAN can sometimes cause [a performance DCHECK in v8](https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/string.h;l=485;drc=4cf7a03ae38ed1bb17c60536b62d7bd39cdf1495) to fail. This is because the `strings` test passes UTF-16 string data as a normal string literal (i.e. `const char*`), meaning what is eventually interpreted as an unsigned `char16_t` may not have the correct alignment.
To be clear, the DCHECK in question seems to only be there for efficiency/correctness of calling code and there is code in place right after it to handle misaligned string data anyway. However, that doesn't stop the test from failing (when v8 is built with DCHECKs on) if the assembler decides to misalign what it thinks is `const char*` data.
I'm upstreaming …

Use utf-16 string literal to fix alignment in `strings` test

---

LICENSE.md

The license file differed enough that licensed did not recognize it.
The link to the contributors was also outdated.

docs: license format and contributors

---

appveyor.yml

As per Feodor Fitsner (Appveyor Support staff):
> There is no x86 build of Node 18.x anymore, so you should [...] change it to:
>
> Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) x64
See Appveyor ticket: https://help.appveyor.com/discussions/problems/31957-please-install-nodejs-v18-new-builds-are-failing-looks-like-node-18-is-missing
This fixes the following error:
```
Running Install scripts
Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
Updating Node.js v18.0.0 (x86)
Uninstalling Node.js v8.17.0 (x86)...
Installing Node.js v18.0.0 (x86)...
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Program Files\AppVeyor\BuildAgent\Modules\nodejs-utils\nodejs-utils.psm1:58 char:5
+ …
```

fix appveyor build tests when x86 binary is not available

---

package.json

Oops!  It looks like we may have forgotten to update this field for a while...
from:
```
"description": "Native Abstractions for Node.js: C++ header for Node 0.8 -> 14 compatibility"
```
to:
```
"description": "Native Abstractions for Node.js: C++ header for Node 0.8 -> 18 compatibility"
```

package.json: fix supported Node.js versions in package description

---

CMakeLists.txt

This commit integrates CMake as an alternative build tool for the project. Users can now choose to use CMake to configure and build the project, in addition to the existing Makefile.

new: Add CMake as an alternative build tool

---

README.md
doc/errors.md
doc/methods.md
doc/persistent.md

This pull request fixes links to the V8 Embedder's Guide in the documentation.

Fix outdated links to V8 documentation

---

nan.h

`ObjectTemplate::SetAccessor` signature has changed in the V8 >= 12, and no longer accepts `v8::AccessControl` parameter. The `v8::AccessControl` enum is in fact a single value now so no public users of nan would be broken if we just stop passing it down to V8.

Fix builds for Electron 29

---

nan.h

Readds the missing trait. Fixes #969.

fix removal of v8::CopyablePersistent

---

README.md
doc/v8_internals.md
nan.h
nan_callbacks.h
nan_callbacks_12_inl.h
nan_scriptorigin.h

I modified some implementations to be able to compile for node version 20.17.0.
This modification may resolve #973 .

Support  for node version 20.17.0

---

nan.h

This should finally close #973. I will let the tests run, expect a release tomorrow.

replace SetAccessor -> SetNativeDataProperty

---

.github/workflows/ci.yml
package.json

Closes: #957
Closes: #985
Closes: #986
Related to: #983
This pull request combines the changes in:
* #985 and
* #957
to provide an upgrade to a version of `node-gyp` that is compatible with Python >= v3.12 that is tested by GitHub Actions on three different operating systems.
Test results:
* https://github.com/cclauss/nan/actions and
* https://ci.appveyor.com/project/RodVagg/nan

Fix compatibility with Python >= 3.12

---

.github/workflows/ci.yml
README.md
appveyor.yml

Test supported Node.js versions before unsupported versions because each test takes ~5 minutes.
Test on the most current Visual Studio possible for each nodejs_version.
Test on the oldest ___supported___ Python version when possible (currently py39).
For all supported Node.js versions also test on the newest Python (currently py313).
* https://devguide.python.org/versions
Visual Studio 2017 image tops out at Python 3.8 which is end-of-life.
Visual Studio 2019 and 2022 images top out at Python 3.13.
`node-gyp` issues related to `nan`: https://github.com/nodejs/node-gyp/issues?q=label%3Anodejs%2Fnan
The Node.js v23 tests are commented out waiting for:
* #979 or similar.
~The Python 3.12 and 3.13 tests are commented out waiting for:~
*  ~#985 because of:~
* ~nodejs/node-gyp#2869~
@kkoopa …

AppVeyor: Test and support versions 8, 10, 12, 14, 16, 17, 18, 19, 20, 21, and 22

---

nan_scriptorigin.h

The current version guard for `Isolate`-less ScriptOrigin constructors checks both `V8_MAJOR_VERSION > 11` and `V8_MINOR_VERSION > 7`. Newer V8s with a minor version not greater than 7, such as V8 v13.2.152.36 of Electron v34.2.0, still fall back to deprecated constructors removed since V8 v12.7.23 and fail to compile.
Fix the preprocessor logic to properly detect V8 v11.7+.

Fix version guard for `ScriptOrigin` constructors

---

.pre-commit-config.yaml
examples/async_pi_estimate/addon.cc
examples/async_pi_estimate/async.cc
examples/async_pi_estimate/pi_est.cc
examples/async_pi_estimate/sync.cc
nan.h
nan_maybe_43_inl.h
nan_maybe_pre_43_inl.h
nan_scriptorigin.h
test/cpp/asyncprogressworker.cpp
test/cpp/asyncprogressworkersignal.cpp
test/cpp/asyncprogressworkerstream.cpp
test/cpp/asyncresource.cpp
test/cpp/asyncworker.cpp
test/cpp/bufferworkerpersistent.cpp
test/cpp/callbackcontext.cpp
test/cpp/methodswithdata.cpp
test/cpp/multifile2.cpp

Fix three cpplint issues:
1. `build/include` --> `build/include_subdir`
2. `build/include_what_you_use`
3. `whitespace/blank_line`
4. `whitespace/line_length` by setting `line-length=88`

Fix four cpplint issues

---

README.md

`npm i --save` has been the default for a long time. This removes it from the readme, also mentions you can use other package managers like yarn and bun.

readme: remove `--save` since that's the default

---

.github/workflows/ci.yml
appveyor.yml
nan_callbacks.h
nan_callbacks_12_inl.h
nan_callbacks_pre_12_inl.h
nan_scriptorigin.h
test/cpp/indexedinterceptors.cpp
test/cpp/namedinterceptors.cpp
test/cpp/news.cpp
test/js/accessors-test.js
test/js/methodswithdata-test.js
test/js/weak-test.js
test/js/weak2-test.js

V8 Was bumped, this would be a patch release, since I already claimed support for Node 23 in 2.22.0.
Also fixes #978.

Support Node 23
