nan.h
This is the correct fix for #239.
=> Fix uv_work_cb versioning

nan_implementation_12_inl.h, nan_implementation_pre_12_inl.h
msvc correctly warns about this
=> Make explicit downcasts of String lengths.

examples/async_pi_estimate/addon.cc, nan.h, nan_implementation_12_inl.h, nan_implementation_pre_12_inl.h, nan_new.h, test/cpp/nannew.cpp, test/cpp/news.cpp
=> Fix compiler warnings.

Makefile, README.md
=> Add details to readme on how to run tests

.travis.yml, appveyor.yml, package.json
=> Test on io.js on Travis

Makefile, nan.h, test/binding.gyp, test/cpp/nancallback.cpp, test/js/nancallback-test.js
=> Made NanCallback::Call accept optional target.

.travis.yml, appveyor.yml, nan.h, test/cpp/morenews.cpp
This should get atom-shell working again.
Addresses #226.
=> Support atom-shell 0.21

nan.h, test/cpp/nancallback.cpp, test/js/nancallback-test.js
new pull request to squash feature to one commit
=> Added comparison operators to NanCallback

README.md
some of #314 fixed but not appveyor; that part still needs fixing.
=> update travis badge and new org addresses

package.json, test/js/news-test.js, test/js/persistent-test.js
=> Fix incorrect, but working test

Makefile, nan.h, test/binding.gyp, test/cpp/trycatch.cpp, test/js/trycatch-test.js
`TryCatch` will start requiring an `Isolate *`.
=> Added NanTryCatch

nan.h, nan_implementation_12_inl.h, nan_implementation_pre_12_inl.h, nan_new.h, test/cpp/morenews.cpp, test/cpp/nannew.cpp, test/cpp/news.cpp
This has been on the list for a long time. Don't really care much for it myself, I think it becomes ugly, but if we are to support lesser compilers, then so be it.
=> Introduce NanNewOneByteString

README.md
I was just getting started with Nan and found the examples were too complex to understand what is necessary for working with Nan versus incidental complexity due to line-endings or monte carlo estimations. It took me hours to get to a point where I felt like I could just get started. Hopefully my work can be the next person's starting point.
Thanks for building and maintaining such a powerful tool.
=> Add link to very simple introductory project

test/cpp/nancallback.cpp, test/js/nancallback-test.js
Refs #362.
R=@kkoopa
It passes for me with io.js, FWIW.
=> Add regression test for Call with custom receiver

Makefile, doc/node_misc.md, nan.h, nan_callbacks_pre_12_inl.h, nan_object_wrap.h
=> Reimplement ObjectWrap from scratch to prevent memory leaks.

doc/object_wrappers.md
Hi there!
I added a missing method on the prototype.
Looks like you need to register all functions.
Thanks!
=> Add prototype method

test/cpp/nannew.cpp
=> Fix endianness problem in test

nan_callbacks_pre_12_inl.h, test/cpp/returnvalue.cpp, test/js/returnvalue-test.js
=> Use NewFromUnsigned in ReturnValue<T>::Set(uint32_t i) for pre_12

README.md
See: https://github.com/nodejs/TSC/issues/92
=> Update DCO to v1.1

nan_object_wrap.h, test/cpp/objectwraphandle.cpp, test/js/objectwraphandle-test.js
Correct solution to #572 with regression test.
=> Make ObjectWrap::handle() const

doc/object_wrappers.md
Add namespace `Nan` for `SetPrototypeMethod`
=> doc/object_wrappers.md: fix basic example

doc/methods.md
Couldn't find links for
> Calls the FunctionTemplate's PrototypeTemplate's Set().
and
> Calls the FunctionTemplate's InstanceTemplate's Set().
=> Updated dead links

test/js/weak-test.js
I do not know why this is necessary, nor if it is the correct fix or simply addresses a symptom. My first guess would be something related to TurboFan. Please take a look.
CI:
https://travis-ci.org/nodejs/nan/builds/265943908
https://ci.appveyor.com/project/RodVagg/nan/build/1348
=> Make garbage collection on the next tick to please Node 8.4

doc/errors.md, doc/maybe_types.md, doc/methods.md, doc/new.md, doc/persistent.md, doc/scopes.md, doc/script.md, doc/v8_internals.md, doc/v8_misc.md
The link of `io.js-3.0` was 404, so I modified it to ~~`node-8.0`~~ `io.js-3.3`
=> Fix broken link

nan.h
`AsyncBareProgressWorker`: move `uv_async_t` and `AsyncWorker` components to non-template class `AsyncBareProgressWorkerBase`
Now that the larger change is merged, I'd like to break `AsyncBareProgressWorker` down into smaller classes so that the base can be reused in yet another worker.  Unfortunately, since this new worker uses a variadic template, it requires c++11.  Without an alternative for older compilers, I don't think this additional new worker actually belongs in _NAN_ until after we drop support for older node versions.
**update:  I was just reading over #676 and it looks like kkoopa and bnoordhuis already agreed that it's OK to use c++11 for new code.  So, after receiving some feedback, I can add the class below to this pull request if desired.
Meanwhile, if we merge this pull …
=> AsyncBareProgressWorker: allow reuse of  uv_async_t and AsyncWorker components

.travis.yml
does someone else want to replace me on this? I don't read them and don't react to them
=> remove my email address from travis

README.md
=> README.md: add mkrufky to WG Members / Collaborators

nan.h
=> Fix deprecation warnings for Node 10

appveyor.yml
* Fix SSL Error: CERT_UNTRUSTED on Appveyor against nodejs version 0.8
* Revert "appveyor.yml: allow failures against nodejs 0.8 (#780)"
=>  Fix SSL Error: CERT_UNTRUSTED on Appveyor against nodejs version 0.8 

package.json
```
"description": "Native Abstractions for Node.js: C++ header for Node 0.8 -> 10 compatibility"
```
closes #803
=> Update package.json description to mention compatibility with Node 10

nan.h
Refs: https://github.com/nodejs/node-addon-api/pull/529#discussion_r331574995
=> Remove unnecessary local variable declaration

doc/methods.md, nan.h, test/binding.gyp, test/cpp/methodswithdata.cpp, test/js/methodswithdata-test.js
This is a similar to pr [602](https://github.com/nodejs/nan/pull/602), I've included tests and documentation changes.
=> Add data to SetMethod and SetPrototypeMethod + documentation + test

test/cpp/weak.cpp, test/cpp/weak2.cpp
By analogy with https://chromium.googlesource.com/v8/v8/+/8c8bd658c6f3a765a73ac49e57b7b138a67db635/test/cctest/test-api.cc#13418
=> test: create HandleScope in weak callback

README.md
=> c++ -> C++ in README.md

nan.h
How about this fix for #807 ? It is very clean, but needs testing on different compilers
=> fix gcc 8 function warning

examples/async_pi_estimate/addon.cc, examples/async_pi_estimate/sync.cc
The async_pi_estimate example could not compile.
=> Fix the example.

package.json
Failure to upgrade is causing a ton of pain at https://github.com/nodejs/node-gyp/issues?q=is%3Aissue+label%3A%22ERR%21+node-gyp+-v+%3C%3D+v5.1.0%22+
=> package.json: Upgrade node-gyp

.github/workflows/ci.yml
@agracio @kkoopa Your review, please.
=> Let's see if CI passes on Node.js v23
